# Site Info
title: SONSAZANG
tagline: '아직 잘 모르는 개발자'
description: '손사장이 되고 싶은 청년 개발자의 이야기'
baseurl: ''
url: http://SONSAZANG.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Sonsazang
  description: A passionate <strong>developer</strong> <br>열심히 하다 보면 언젠가 만나겠지
  contact:
    github:    https://github.com/SONSAZANG/SONSAZANG.github.io
    # facebook:  <hide>
    # twitter:   <hide>
    email: mailto:kekekee257@gmail.com 
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    # - { Categories: '/blog/categories/#Github_Pages' }
    # - { Tags: '/blog/tags/#Git' }
    - { Github Pages: '/blog/categories/#Github_Pages'}
    - { Git: '/blog/categories/#Git'}

  About:          
    - '/about/'
  Github Project: 
    - 'http://SONSAZANG.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Step by step goes a long way
# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

